FitnessPanelMVC.web/Controllers/BodyIndicatorController.cs
using FitnessPanelMVC.Application.Interfaces;
using FitnessPanelMVC.Application.Services;
using FitnessPanelMVC.Application.Validators;
using FitnessPanelMVC.Application.ViewModels.BodyIndicator;
using FitnessPanelMVC.Application.ViewModels.Product;
using FitnessPanelMVC.Application.ViewModels.UserReportFile;
using FitnessPanelMVC.Domain.Model;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FitnessPanelMVC.web.Controllers
{
    [Authorize]
    public class BodyIndicatorController : Controller
    {
        private readonly IBodyIndicatorService _bodyIndicatorService;

        private readonly IUserReportService _userReportService;

        private readonly IValidator<NewBodyIndicatorVm> _validator;

        private readonly IWebHostEnvironment _hostEnvironment;

        private readonly IUserService _userService;

        public BodyIndicatorController(IBodyIndicatorService bodyIndicatorService,
            IUserReportService userReportService,
            IValidator<NewBodyIndicatorVm> validator,
            IUserService userService,
            IWebHostEnvironment hostEnvironment)
        {
            _bodyIndicatorService = bodyIndicatorService;
            _userReportService = userReportService;
            _validator = validator;
            _userService = userService;
            _hostEnvironment = hostEnvironment;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = await _userService.GetIdAsync(User);
            var model = await _userReportService.GetUserBodyReportsAsync(userId);
           

            return View(model);
        }

        public async Task<FileResult> DownloadReport(string filePath)
        {
            var mimeType = "application/pdf";
            var fileFullPath = Path.Combine(_hostEnvironment.WebRootPath, filePath);
            var fileBytes = await System.IO.File.ReadAllBytesAsync(fileFullPath);
            var fileName = Path.GetFileName(filePath);

            return File(fileBytes, mimeType, fileName);
        }

        [HttpGet]
        public IActionResult CreateBodyIndicator()
        {
            var model = new NewBodyIndicatorVm();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateBodyIndicator(NewBodyIndicatorVm newBodyIndicatorVm)
        {
            var userId = await _userService.GetIdAsync(User);
            var result = await _validator.ValidateAsync(newBodyIndicatorVm);
            if (result.IsValid)
            {
                int id = await _bodyIndicatorService.AddNewAsync(newBodyIndicatorVm, userId);
                var bodyIndicator = await _bodyIndicatorService.GetByIdAsync(id);
                await _userReportService.CreateUserBodyReportAsync(bodyIndicator, userId);
                return RedirectToAction("Index");
            }

            return View(newBodyIndicatorVm);
        }
    }
}

FitnessPanelMVC.web/Views/BodyIndicator/CreateBodyIndicator.cshtml
@model FitnessPanelMVC.Application.ViewModels.BodyIndicator.NewBodyIndicatorVm

@{
    ViewData["Title"] = "CreateBodyIndicator";
    var PALSelectList = new SelectList(Enum.GetValues(typeof(FitnessPanelMVC.Domain.Enums.PAL)));
    var sexOptions = new List<SelectListItem>
{
    new SelectListItem { Value = "male", Text = "Male" },
    new SelectListItem { Value = "female", Text = "Female" }
};

    var sexSelectList = new SelectList(sexOptions, "Value", "Text");
}

<h1>Create Body Indicators Profile</h1>

<h4>BMIFormVm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateBodyIndicator">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Sex" class="control-label"></label>
                @Html.DropDownListFor(model => model.Sex, sexSelectList, "Chose your sex", new { @class = "form-control" })
                <span asp-validation-for="Sex" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mass" class="control-label"></label>
                <input asp-for="Mass" class="form-control" />
                <span asp-validation-for="Mass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Height" class="control-label"></label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PAL" class="control-label"></label>
                @Html.DropDownListFor(model => model.PAL, PALSelectList, "Chose your activity", new { @class = "form-control" })
                <span asp-validation-for="PAL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HipCircumference" class="control-label"></label>
                <input asp-for="HipCircumference" class="form-control" />
                <span asp-validation-for="HipCircumference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AbdominalCircumference" class="control-label"></label>
                <input asp-for="AbdominalCircumference" class="form-control" />
                <span asp-validation-for="AbdominalCircumference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FitnessPanelMVC.web/Views/BodyIndicator/CreateBodyIndicatorPartial.cshtml
@model FitnessPanelMVC.Application.ViewModels.BodyIndicator.NewBodyIndicatorVm

@{
    ViewData["Title"] = "CreateBodyIndicator";
    var PALSelectList = new SelectList(Enum.GetValues(typeof(FitnessPanelMVC.Domain.Enums.PAL)));
    var sexOptions = new List<SelectListItem>
{
    new SelectListItem { Value = "male", Text = "Male" },
    new SelectListItem { Value = "female", Text = "Female" }
};

    var sexSelectList = new SelectList(sexOptions, "Value", "Text");
}

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="CreateBodyIndicator">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="UserId" />
            <input type="hidden" asp-for="Date" />

            <div class="form-group">
                <label asp-for="Sex" class="control-label"></label>
                @Html.DropDownListFor(model => model.Sex, sexSelectList, "Chose your sex", new { @class = "form-control" })
                <span asp-validation-for="Sex" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mass" class="control-label"></label>
                <input asp-for="Mass" class="form-control" />
                <span asp-validation-for="Mass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Height" class="control-label"></label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PAL" class="control-label"></label>
                @Html.DropDownListFor(model => model.PAL, PALSelectList, "Chose your activity", new { @class = "form-control" })
                <span asp-validation-for="PAL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HipCircumference" class="control-label"></label>
                <input asp-for="HipCircumference" class="form-control" />
                <span asp-validation-for="HipCircumference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AbdominalCircumference" class="control-label"></label>
                <input asp-for="AbdominalCircumference" class="form-control" />
                <span asp-validation-for="AbdominalCircumference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="form-check">
                    <input asp-for="IsRealUserData" class="form-check-input" />
                    <label asp-for="IsRealUserData" class="form-check-label">This is User data (will be used to follow your progress)</label>
                </div>
                <span asp-validation-for="IsRealUserData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

FitnessPanelMVC.web/Views/BodyIndicator/Index.cshtml
@using FitnessPanelMVC.Application.ViewModels.BodyIndicator;
@model ICollection<FitnessPanelMVC.Application.ViewModels.UserReportFile.UserReportForListVm>

@{
    ViewData["Title"] = "Dashboard";
}

<div class="container mt-4">

    <div class="row">
        <div class="col-md-6">
            <h2>Recent Reports</h2>
            <div class="list-group">
                @if (Model != null && Model.Any())
                {
                    foreach (var report in Model)
                    {
                        <a href="@Url.Action("DownloadReport", "BodyIndicator", new { filePath = report.Path })" target="_blank" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                            <span class="me-auto">
                                <i class="fa-solid fa-file-pdf me-2"></i>
                                Report - @report.CreationDate.ToShortDateString()
                            </span>
                            <span class="badge bg-primary rounded-pill">PDF</span>
                        </a>
                    }
                }
                else
                {
                    <p class="text-muted">No reports to display.</p>
                }
            </div>
        </div>
        <div class="col-md-6">
            <h2>Create New Report</h2>

            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createReportModal">
                Add Report
            </button>


            <div class="modal fade" id="createReportModal" tabindex="-1" aria-labelledby="createReportModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="createReportModalLabel">New Report</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            @Html.Partial("CreateBodyIndicatorPartial", new NewBodyIndicatorVm())
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
}