FitnessPanelMVC.web/Controllers/MealController.cs
using FitnessPanelMVC.Application.Interfaces;
using FitnessPanelMVC.Application.Services;
using FitnessPanelMVC.Application.ViewModels.Meal;
using FitnessPanelMVC.Application.ViewModels.MealProduct.TransferModel;
using FitnessPanelMVC.Application.ViewModels.Product;
using FitnessPanelMVC.Domain.Model;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace FitnessPanelMVC.web.Controllers
{
    [Authorize]
    public class MealController : Controller
    {
        private readonly IMealService _mealService;

        private readonly IProductService _productService;

        private readonly IUserService _userSerivce;

        public MealController(IMealService mealService, IProductService productService, IUserService userService)
        {
            _mealService = mealService;
            _productService = productService;
            _userSerivce = userService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = await _userSerivce.GetIdAsync(User);
            var model = await _mealService.GetForListByDate(DateTime.Now, userId);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(DateTime date)
        {
            var userId = await _userSerivce.GetIdAsync(User);
            var model = await _mealService.GetForListByDate(date, userId);
            return View(model);
        }

        [HttpGet]
        public IActionResult AddMeal()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddMeal(NewMealVm newMealVm)
        {
            var userId = await _userSerivce.GetIdAsync(User);
            int id = await _mealService.AddNewAsync(newMealVm, userId);
            HttpContext.Session.SetInt32("CurrentMealId", id);
            return RedirectToAction("AddProductsToMealList");
        }

        [HttpGet]
        public async Task<IActionResult> AddProductsToMealList()
        {
            var userId = await _userSerivce.GetIdAsync(User);
            var model = await _productService.GetAllForListAsync(20, 1, "", userId);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddProductsToMealList(int pageSize, int? pageNo, string searchString)
        {
            var userId = await _userSerivce.GetIdAsync(User);
            if (!pageNo.HasValue)
            {
                pageNo = 1;
            }
            if (searchString is null)
            {
                searchString = String.Empty;
            }
            var model = await _productService.GetAllForListAsync(pageSize, pageNo.Value, searchString, userId);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddProductToMeal([FromBody] ProductMealModel model)
        {
            int mealId = HttpContext.Session.GetInt32("CurrentMealId") ?? default;
            await _mealService.AddProductToMealAsync(model.ProductId, mealId, model.Weight);
            return Json(new { success = true, message = "Product added successfully" });
        }

        public async Task<IActionResult> DeleteMeal(int id)
        {
            await _mealService.DeleteByIdAsync(id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> MealDetails(int id)
        {
            HttpContext.Session.SetInt32("CurrentMealId", id);
            var model = await _mealService.GetDetailsByIdAsync(id);
            return View(model);
        }

        public async Task<IActionResult> DeleteProductFromMeal(int id, int mealId)
        {
            await _mealService.DeleteProductFromMealByIdAsync(id, mealId);
            return RedirectToAction("Index");
        }
    }
}

FitnessPanelMVC.web/Views/Meal/AddMeal.cshtml
@model FitnessPanelMVC.Application.ViewModels.Meal.NewMealVm

@{
    ViewData["Title"] = "Add Meal";
    var mealTypeSelectList = new SelectList(Enum.GetValues(typeof(FitnessPanelMVC.Domain.Enums.MealType)));
}

<h1>Add Meal</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddMeal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="TotalCalories" />
            <input type="hidden" asp-for="TotalCarbs" />
            <input type="hidden" asp-for="TotalFat" />
            <input type="hidden" asp-for="TotalProtein" />

            <div class="form-group">
                <label asp-for="MealType" class="control-label"></label>
                @Html.DropDownListFor(model => model.MealType, mealTypeSelectList, "Choose Meal Type", new { @class = "form-control" })
                <span asp-validation-for="MealType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MealDate" class="control-label"></label>
                <input asp-for="MealDate" class="form-control" />
                <span asp-validation-for="MealDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

FitnessPanelMVC.web/Views/Meal/AddProductsToMealList.cshtml
@model FitnessPanelMVC.Application.ViewModels.Product.ListProductForListVm

@{
    ViewData["Title"] = "AddProductsToMealList";
}

<div class="container mt-5">
    <h1 class="mb-4">Products list</h1>



    <form asp-action="AddProductsToMealList" asp-controller="Meal" method="post" id="searchForm">
        
        <div class="input-group mb-3">
            <input type="text" class="form-control" asp-for="SearchString" name="searchString" id="searchString" placeholder="Search for products...">
            <button class="btn btn-outline-secondary" type="submit">Search</button>
        </div>

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>CaloriesPer100g</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Products)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Id)</td>
                            <td>@Html.DisplayFor(modelItem => item.Name)</td>
                            <td>@Html.DisplayFor(modelItem => item.CaloriesPer100g)</td>
                            <td>
                                <a href="javascript:void(0);" onclick="showPopup('@item.Id')" class="btn btn-warning btn-sm">Add</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        @{
            int currentPage = Model.CurrentPage;
            int totalPages = (int)Math.Ceiling(Model.Count / (double)Model.PageSize);
            int startPage = currentPage - 2;
            int endPage = currentPage + 2;

            if (startPage <= 0)
            {
                endPage -= (startPage - 1);
                startPage = 1;
            }

            if (endPage > totalPages)
            {
                endPage = totalPages;
                if (endPage > 5)
                {
                    startPage = endPage - 4;
                }
            }
        }

        <nav aria-label="Page navigation">
            <ul class="pagination">
                @for (int i = startPage; i <= endPage; i++)
                {
                    <li class="page-item @(i == currentPage ? "active" : "")">
                        <a href="javascript:PagerClick(@i)" class="page-link">@i</a>
                    </li>
                }
            </ul>
        </nav>


        <input type="hidden" name="pageNo" id="pageNo" />
        <input type="hidden" name="pageSize" id="pageSize" value="20" />
    </form>
</div>
<div class="mt-4">
    <a href="@Url.Action("Index")" class="btn btn-secondary">Back to List</a>
</div>

<!-- Popup Modal -->
<div id="popupModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <form id="addProductForm">
            <h2>Add Product</h2>
            <input type="hidden" id="selectedProductId" name="productId"/>
            <label for="weight">Weight:</label>
            <input type="number" id="weight" name="weight" required/>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

<style>
    .modal { display: none; position: fixed; z-index: 1; left: 0; top: 0; width: 100%; height: 100%; overflow: auto; background-color: rgb(0,0,0); background-color: rgba(0,0,0,0.4); }
    .modal-content { background-color: #fefefe; margin: 15% auto; padding: 20px; border: 1px solid #888; width: 80%; }
    .close { color: #aaa; float: right; font-size: 28px; font-weight: bold; }
    .close:hover, .close:focus { color: black; text-decoration: none; cursor: pointer; }
</style>

@section Scripts
    {
    <script type="text/javascript">
        function PagerClick(index) {
            document.getElementById("pageNo").value = index;
            document.getElementById("searchForm").submit();
        }

        var modal = document.getElementById("popupModal");
        var span = document.getElementsByClassName("close")[0];

        span.onclick = function () {
            modal.style.display = "none";
        }
        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }

        function showPopup(productId) {
            document.getElementById("selectedProductId").value = productId;
            modal.style.display = "block";
        }
        document.getElementById("addProductForm").onsubmit = function (event) {
            event.preventDefault();

            var productId = document.getElementById("selectedProductId").value;
            var weight = document.getElementById("weight").value;

            fetch('/Meal/AddProductToMeal', {
                method: 'POST',
                body: JSON.stringify({ productId: productId, weight: weight }),
                headers: {
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                if (response.ok) {
                    return response.json();
                }
                throw new Error('Something went wrong');
            })
                .then(data => {
                    console.log(data);
                    modal.style.display = "none";
                }).catch(error => {
                    console.error('Error:', error);
                });
        }
    </script>
}

FitnessPanelMVC.web/Views/Meal/Index.cshtml
@model FitnessPanelMVC.Application.ViewModels.Meal.ListMealForListVm

@{
    ViewData["Title"] = "Meal Overview";
}

<h1>Meal Overview</h1>
<p>Here you can view and manage your daily meals.</p>

<div class="row">
    <div class="col-12">
        <form method="post" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="date" id="date" name="date" placeholder="Select Date" aria-label="Select Date" style="max-width: 200px;">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Load Meals</button>
            <a asp-action="AddMeal" class="btn btn-primary ml-2">Add New Meal</a>
        </form>
    </div>
</div>

<div class="total-nutrition-values d-flex justify-content-end" style="margin-top: -90px;">
    <div class="nutrition-card" style="background-color: white; border: 1px solid #ddd; padding: 10px; margin-left: 10px; ">
        <div class="nutrition-title">Calories</div>
        <div class="nutrition-value">@Model.Meals.SelectMany(m => m.MealProducts).Sum(mp => mp.Calories).ToString("F2")</div>
    </div>
    <div class="nutrition-card" style="background-color: white; border: 1px solid #ddd; padding: 10px; margin-left: 10px;">
        <div class="nutrition-title">Proteins</div>
        <div class="nutrition-value">@Model.Meals.SelectMany(m => m.MealProducts).Sum(mp => mp.Protein).ToString("F2")</div>
    </div>
    <div class="nutrition-card" style="background-color: white; border: 1px solid #ddd; padding: 10px; margin-left: 10px;">
        <div class="nutrition-title">Carbs</div>
        <div class="nutrition-value">@Model.Meals.SelectMany(m => m.MealProducts).Sum(mp => mp.Carbs).ToString("F2")</div>
    </div>
    <div class="nutrition-card" style="background-color: white; border: 1px solid #ddd; padding: 10px; margin-left: 10px;">
        <div class="nutrition-title">Fat</div>
        <div class="nutrition-value">@Model.Meals.SelectMany(m => m.MealProducts).Sum(mp => mp.Fat).ToString("F2")</div>
    </div>
</div>

<div class="row mt-4">
    <div class="col-md-12">
        <table class="table table-responsive table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>Meal Information</th>
                    <th>Products</th>
                    <th width="300">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var meal in Model.Meals)
                {
                    <tr>
                        <td>
                            <div>
                                <strong>@meal.MealType</strong>
                                <span class="text-muted" style="font-size: small;"> (@meal.MealDate.ToString("HH:mm"))</span>
                            </div>
                            <table class="table table-sm mt-2">
                                <tr><td>Calories:</td><td>@meal.TotalCalories.ToString("F2")</td></tr>
                                <tr><td>Proteins:</td><td>@meal.TotalProtein.ToString("F2")</td></tr>
                                <tr><td>Carbs:</td><td>@meal.TotalCarbs.ToString("F2")</td></tr>
                                <tr><td>Fat:</td><td>@meal.TotalFat.ToString("F2")</td></tr>
                            </table>
                        </td>
                        <td>
                            <ul>
                                @foreach (var product in meal.MealProducts)
                                {
                                    <li>@product.ProductName: @product.Weight g</li>
                                }
                            </ul>
                        </td>
                        <td class="align-middle">
                            <a asp-action="MealDetails" asp-route-id="@meal.Id" class="btn btn-info btn-sm">Manage</a>
                            <a asp-action="DeleteMeal" asp-route-id="@meal.Id" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

FitnessPanelMVC.web/Views/Meal/MealDetails.cshtml
@model FitnessPanelMVC.Application.ViewModels.Meal.MealForListVm

@{
    ViewData["Title"] = "Meal Details";
}

<h1>Meal Details</h1>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">@Model.MealType</h4>
        <p class="card-text">
            <strong>Date:</strong> @Model.MealDate.ToString("dd-MM-yyyy HH:mm") <br>
            <strong>Total Calories:</strong> @Model.TotalCalories.ToString("F2") <br>
            <strong>Total Carbs:</strong> @Model.TotalCarbs.ToString("F2") g<br>
            <strong>Total Fat:</strong> @Model.TotalFat.ToString("F2") g<br>
            <strong>Total Protein:</strong> @Model.TotalProtein.ToString("F2") g
        </p>
    </div>
</div>

<h3 class="mt-4">Products in this Meal</h3>

<table class="table table-striped mt-3">
    <thead>
        <tr>
            <th>Product Name</th>
            <th>Weight (g)</th>
            <th>Proteins</th>
            <th>Carbs</th>
            <th>Fat</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.MealProducts)
        {
            <tr>
                <td>@product.ProductName</td>
                <td>@product.Weight</td>
                <td>@product.Protein g</td>
                <td>@product.Carbs g</td>
                <td>@product.Fat g</td>
                <td>
                    <a href="@Url.Action("DeleteProductFromMeal", new { id = product.ProductId, mealId = Model.Id })" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="mt-4">
    <a href="@Url.Action("AddProductsToMealList")"  class="btn btn-primary">Add products</a>
    <a href="@Url.Action("Index")" class="btn btn-secondary">Back to List</a>
</div>